#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.9.8-jdk-21
definitions:
  - step: &test
      name: Testing ...
      caches:
          - maven
      script: # Modify the commands below to build your repository.
        - mvn -B verify --file pom.xml # -B batch mode makes Maven less verbose
pipelines:
  branches:
    staging:
      - step:
          <<: *test
          name: Test beta version
          deployment: beta
  tags:
    '*-beta*':
      - step:
          <<: *test
          name: Test beta version
          deployment: beta