image: maven:3.9.8-jdk-11
definitions:
  steps:
    - step: &test
        name: Testing ...
        caches:
            - maven
        script: # Modify the commands below to build your repository.
          - mvn -B verify --file pom.xml # -B batch mode makes Maven less verbose
pipelines:
  branches:
    staging:
      - step:
          <<: *test
          name: Test beta version
          deployment: Staging
  tags:
    '*-beta*':
      - step:
          <<: *test
          name: Test beta version
          deployment: Staging