image: maven:3.9.8-jdk-21
definitions:
  - step: &test
      name: Testing ...
      caches:
          - maven
      script: # Modify the commands below to build your repository.
        - mvn -B verify # -B batch mode makes Maven less verbose
pipelines:
  branches:
    staging:
      - step:
          <<: *test
          name: Test beta version
          deployment: beta
  tags:
    '*-beta*':
      - step:
          <<: *test
          name: Test beta version
          deployment: beta